deliveryhero/go-ranger

example.go, ranger_logger/logrus.go
https://foodpanda.atlassian.net/browse/ORDER-196
tl;dr in production we need to use stdout
=> Added new logger constructor

example.go, ranger_logger/logrus.go
Client using the logger should be able to choose the formatter to be used.
=> Inject formatter on logger constructors

example.go, ranger_logger/logrus.go
I think would be better to create wrappers for external types, making it easier to use the toolkit
=> add wrapper for logrus types

ranger_http/health_check.go
It is good to know how long each health check service took to identify problems.
=> Add time to health check services

ranger_http/health_check.go
The sim of time elapsed for all service checks should be at root level.
=> Add general time elapsed for all service checks

ranger_http/handler.go, ranger_http/response_writer.go, ranger_http/server.go
Export WriteErrorResponse, add ErrorResponseData struct and remove ResponseWriter struct.
=> Refactoring response writer

.gitignore, glide.lock, glide.yaml, ranger_http/client.go, ranger_http/client_mock.go, ranger_http/hateos.go, ranger_http/hateos_test.go
https://foodpanda.atlassian.net/browse/DISCOVER-542
=> DISCOVER-542 Implement HATEOS for next page requests

ranger_logger/logrus.go
https://foodpanda.atlassian.net/browse/DISCOVER-601
=> DISCOVER-601 Standardize time logging in our go apps

.travis.yml, pre-commit.dist, ranger_http/client.go, ranger_http/response_writer.go, ranger_http/server.go
- add pre-commit.dist
- add gofmt to .travis.yml
- remove all existing issues via gofmt
=> No-ticket: add pre-commit hook.

example.go, ranger_http/health_check.go, version.json
Change health check to follow the team standards
- Added to top level
- Removed as regular check
- Replaced with some dummy example health check
=> POST-937 Move version to top level health check

ranger_http/health_check.go
New version:
```
{
"http-status": 200,
"version": {
"tag": "POST-885_Build_The_App",
"commit": "218fda7c281857fd4ed3ca9075fe6c1f7a741f83"
},
"time": 2.628e-06,
"status": true,
"hostname": "jsa.local",
"checks": {
"Dummy": {
"status": true,
"time": 7.25e-07,
"info": "I'm awake!"
}
}
}
```
=> Change order of elements on health check

ranger_http/health_check.go, ranger_http/middleware.go, ranger_http/response_writer.go
=> Correct status on health check and log response status

ranger_metrics/newrelic.go
do not trigger alarms for 400 bad request
=> ignore badrequest new relic

ranger_metrics/newrelic.go
Added the ability to configure the newrelic instance.
=> Ranger new newrelic with config

fdapm/apmmock/newrelic_transaction.go, go.mod, go.sum
Newrelic interface changed, so the mocks need to be updated
=> update newrelic and mocks

fdhttp/fdhandler/health_check.go
I had to dig into the code to understand what this should mean. We can save the next person the trouble.
=> Document semantics of "status" field

pubsub/awssub/sub.go, pubsub/pubsub.go
expose sqs message id via getter
=> Add MessageID getter to Message struct

fdhttp/server.go
Currently go-ranger doesn't provide a possibility to change any server timeouts (read/write/idle). All values are hardcoded and can not be overwritten.
This PR makes all server timeouts configurable and keeps the default values as it is now.
=> Optional server timeouts

fdhttp/fdhandler/health_check.go
=> NO_TICKET. Registering a health check callback now will not lead to a data race

pubsub/awspub/pub.go, pubsub/awspub/pub_test.go, pubsub/pubsub.go
Add new method for publishing in specific topic, needed for subscription to be able to easily deploy to different countries from a regional application
Tested in ST
=> GROWTH-2999 Add new method for publishing in specific topic

go.mod, go.sum, ranger_http/server.go
the throttle library has changed hosting over to GitHub so a simple change to fix this issue
https://github.com/throttled/throttled/issues/44
=> Bug fixes to resolve import issues

README.md
Since the project is no longer actively maintained I suggest to mark it as DEPRECATED in readme file.
=> README - deprecated
