- example.go
- ranger_http/health_check.go
Use "func" to define health check services. It is necessary because for each request the values about the "checks" should be updated based on the logic for each "check". (for exemple the connection with DB, for each request we should check again). I used `func` because is a generic and unrestricted way to do it.
> Use "func" to define health check services

- ranger_http/client.go
It does not make sense to do that here, otherwise we would need to check for all 2xx statuses because they are all valid. This is responsibility of the client using the library.
> Remove check for 200 in client request

- ranger_http/client.go
[POST-980](https://foodpanda.atlassian.net/browse/POST-980)
Just return the original error also after formatted, as a developer, I need to know the exact error.
> Put the exactly error in fmt error returning

- ranger_logger/logrus.go
Problem:
The log for client ip in ranger_logger was set to remote address.  The remote address is composed 
of {ip}:{port}. Because of this structure, kibana is not able to parse the log and therefore, these logs 
are not shown on the platform.
Proposition:
Just change the remoteAddr to X-Forwarded-For http header field. As shown in the changes of this 
pull request.
> Change the log with remote address to header[X-Forwarded-For]

- ranger_logger/logrus.go
As foodora Kibana implementation uses a prefix to enable unknown fields to be used in filters, I'm adding a new field in the log wrapper.
How to use it:
```go
logger := ranger_logger.NewLogger(
os.Stdout,
ranger_logger.LoggerData{
"env":           Env.Environment,
"appName": Env.AppName,
},
ranger_logger.GetJSONFormatter(),
Env.LogLevel,
)
logger.(*ranger_logger.Wrapper).SetPrefix("ctx")
```
> Add extra fields prefix

- ranger_metrics/newrelic.go
To be able to add a newrelic custom parameter, we forward a newrelic transaction instance through a request context
> ranger metrics: add newrelic trans to request context

- fdhttp/server.go
Requests with no timeouts lead to memory leaks from unclosed goroutines in the http server connection pool, and expose the http.Server instance for overriding defaults
https://blog.cloudflare.com/exposing-go-on-the-internet/#timeouts
> Add http.Server default timeouts

- pubsub/awssub/sub.go
- pubsub/pubsub.go
To handle cases when a message was read from a queue several times we should and an attribute to the request to sqs and expose a getter for that value.
> Add received count getter to Message struct

- pubsub/awssub/sub.go
- pubsub/awssub/sub_test.go
few fixes related to aws subscriber:
- deadlock occurs if the subscriber is stopped and received messages from aws waiting for a space in output channel, at that a consumer does not read from the output channel as it has stopped the subscriber.
- removed messages are not flushed from the buffer after the subscriber is stopped and as a result handled and removed messages are not removed from sqs queue.
- err var is not set to nil after each delete iteration.
- stop all goroutine when the subscriber is being stopped
- do not add a removed message to delete buffer if the subscriber is not running
> bugfix: deadlock; flush delete buffer after stopping the subscriber

- fdhttp/client_test.go
The removing test is not correct and redundant.
Redundant because it is testing a http client max idle connection feature which is coming from the standard `http` package.
Its not correct because it fails from time to time and the reason is that the connection closing could happened concurrently and not the all connections are closed before we check the number of active connections.
> remove redundant TestClient_MaxIdleConns unit test

- pubsub/awssub/sub.go
Awssub remove a redundant debug log as was suggested here https://github.com/foodora/go-ranger/pull/71
> Awssub remove a redundant debug log

- pubsub/awssub/sub.go
Currently there is not way to handle errors in case if sqs is not reachable. 
In case of an error the lib writes log and write error to `sqsErr` subscriber field. That field is not useful for clients, since we can not read and reset it safely.
To provide an error handling for clients we introduce `onErrorFunc` which will be called if an error occurs.
> introduce error handling function

- pubsub/pubsub.go
In the previous PR we introduced an error handler function for aws subscriber but missed to add a setter for it to the aws subscriber interface.
In this PR we adding it.
> Add setter for on error func handler

- fddb/config.go
- fddb/config_test.go
The [Go-MySQL-Driver](https://github.com/go-sql-driver/mysql#connection-pool-and-timeouts) package supports `timeout` parameters but the current implementation in go-ranger does not support DSN parameters.
The DSN MySql string supports three timeout parameters `readTimeout`, `writeTimeout` and `timeout`.
This PR introduces the usage of DSN parameters as part of the connection string by exposing the timeout parameters in the `DBConfig` struct.
> Add timeout parameters to mysql driver

- fdhttp/fdhandler/health_check.go
- fdhttp/fdhandler/health_check_test.go
With this feature, you can pass static extra params to be shown on health-check page.
You can do it like this:
```
extra := map[string]string{
"param1": "val1",
"param2": "val2",
}
_ = fdhandler.NewHealthCheck(gitTag, gitHash).
WithExtraParams(extra)
```
> NO_TICKET. A way to pass extra params for health check output

- fdapm/newrelic_middleware.go
Grouping by Path create issues on NewRelic, which may lead to getting blocked by them, making new metrics not appear
> fix newrelic transaction grouping

- pubsub/awssub/sub.go
There is no way now to write a log specifically with debug level.
Most loggers use Printf to wrap Info log, as a result we write debug logs as info.
> awssub remove incorrect debug log

- fdhttp/router.go
- fdhttp/router_test.go
StdHandlers inherit Parent router's middlewares.
fdhttp.Handler interfaces don't.
So with this solution I recursively go parent by parent and wrap my handler with their middlewares.
**Backwards compatibility** - if someone redeclare a list of middlewares in each subrouter they would start run them many times.
p.s. I've added tests as well.
> inherit middlewares of parent routers

- fdapm/apmmock/newrelic_transaction.go
- go.mod
- go.sum
- updated newrelic go-agent version: v2.7.0 -> v3.3.0
- updated the implementation of newrelic Transaction mock with new methods
> Update newrelic transaction mock

- fdhttp/fdhandler/health_check.go
- fdhttp/fdhandler/health_check_test.go
This change is to mitigate a security concern that exposing system version could increase attack vector for the applications
> POP-564 remove system version health check endpoint

- README.md
- fddb/config.go
- fddb/config_test.go
Over the weekend of 11th, 12th July an incident where a failover of database by
AWS resulted in errors on archimedes consumer due to a switch of a writer to a
reader. Archimedes consumer and other applications could not automatically
recover as expected during the incident.
This is because the mysql driver held the connection open with the read-only
replica. To ensure that this doesn't occur again, we want to enable the
https://github.com/go-sql-driver/mysql#rejectreadonly option. Add this option to
the MysqlOptions so that users of the library can add it if necessary.
https://jira.deliveryhero.com/browse/CART-3403
Also, small changes following the boy scout rule :D
> Mysql add reject read only
